-- MySQL Script generated by MySQL Workbench
-- Tue May 12 15:28:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema idmanager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema idmanager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `idmanager` DEFAULT CHARACTER SET utf8 ;
USE `idmanager` ;

-- -----------------------------------------------------
-- Table `idmanager`.`tbl_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idmanager`.`tbl_users` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(100) NULL,
  `status` ENUM('0', '1') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idmanager`.`tbl_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idmanager`.`tbl_category` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idmanager`.`tbl_database`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idmanager`.`tbl_database` (
  `id` INT NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `link` VARCHAR(255) NOT NULL,
  `status` ENUM('0', '1') NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `tbl_category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_database_tbl_category_idx` (`tbl_category_id` ASC) ,
  CONSTRAINT `fk_tbl_database_tbl_category`
    FOREIGN KEY (`tbl_category_id`)
    REFERENCES `idmanager`.`tbl_category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
